name: CI


on:
  push:
    branches: 
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Copying website over!
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v1.1.0
      with:
        # FTP host
        host: 
        # FTP user
        user: ${{ FTP_USER }}
        # FTP password
        password: ${{ FTP_USER_PASS }}
        # Local directory
        localDir: # optional, default is .
        # Remote directory
        remoteDir: /demo.zach-martin.com
        
